// Codegen: turn flagpack-core SVGs into typed, tree-shakeable React components.
//
// Reads flagpack-core from node_modules (devDependency, never shipped at runtime)
// and emits:
//   src/flags/<CODE>.tsx   one component per country (SVGR + SVGO)
//   src/flags/index.ts     barrel of FlagXX exports
//   src/registry.ts        lazy loaders, names, alpha-3/numeric aliases, resolveCode()
//   src/types.ts           CountryCode / Alpha3Code unions
//
// Run with: npm run generate
import { transform } from "@svgr/core";
import { createRequire } from "node:module";
import {
  readFileSync,
  writeFileSync,
  mkdirSync,
  existsSync,
  rmSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");

const fpDir = dirname(require.resolve("flagpack-core/package.json"));
const list = JSON.parse(
  readFileSync(join(fpDir, "countryCodeList.json"), "utf8"),
);

const flagsDir = join(root, "src", "flags");
rmSync(flagsDir, { recursive: true, force: true });
mkdirSync(flagsDir, { recursive: true });

// flagpack ships hand-tuned svgs at three widths; the largest is the highest
// fidelity and scales down cleanly, so we use it as the single source per flag.
const SIZE_PREFERENCE = ["l", "m", "s"];

function readSvg(code) {
  for (const size of SIZE_PREFERENCE) {
    const p = join(fpDir, "svg", size, `${code}.svg`);
    if (existsSync(p)) return readFileSync(p, "utf8");
  }
  return null;
}

// v1 ships standard ISO 3166-1 countries only. flagpack also bundles a handful
// of subdivisions (e.g. GB-ENG, BQ-BO) with hyphenated codes and no
// alpha-3/numeric; those are deferred to a later release.
const isStandardCountry = (entry) =>
  /^[A-Z]{2}$/.test(entry.alpha2 || "") && entry.alpha3 && entry.numeric;

const generated = [];

for (const entry of list) {
  const code = entry.alpha2;
  if (!isStandardCountry(entry)) continue;
  const svg = readSvg(code);
  if (!svg) {
    console.warn(`[flaglet] no svg for ${code} (${entry.countryName}), skipping`);
    continue;
  }

  const componentName = `Flag${code}`;
  const tsx = await transform(
    svg,
    {
      typescript: true,
      dimensions: true,
      exportType: "default",
      expandProps: "end",
      jsxRuntime: "automatic",
      // Baked-in accessibility; consumers can override via props.
      svgProps: { role: "img", "aria-label": entry.countryName },
      svgo: true,
      svgoConfig: {
        plugins: [
          {
            name: "preset-default",
            params: { overrides: { removeViewBox: false } },
          },
          // Prefix internal ids per country so inlined <clipPath>/<mask>
          // references never collide across different flags.
          { name: "prefixIds", params: { prefix: code.toLowerCase() } },
        ],
      },
      plugins: ["@svgr/plugin-svgo", "@svgr/plugin-jsx"],
    },
    { componentName },
  );

  writeFileSync(join(flagsDir, `${code}.tsx`), tsx);
  generated.push(entry);
}

generated.sort((a, b) => a.alpha2.localeCompare(b.alpha2));

const quote = (s) => JSON.stringify(s);
const union = (arr) => arr.map((s) => `"${s}"`).join("\n  | ");

// src/flags/index.ts
writeFileSync(
  join(flagsDir, "index.ts"),
  "// AUTO-GENERATED by scripts/generate.mjs. Do not edit.\n" +
    generated
      .map((c) => `export { default as Flag${c.alpha2} } from "./${c.alpha2}";`)
      .join("\n") +
    "\n",
);

// src/types.ts
writeFileSync(
  join(root, "src", "types.ts"),
  `// AUTO-GENERATED by scripts/generate.mjs. Do not edit.
import type * as React from "react";

export type CountryCode =
  | ${union(generated.map((c) => c.alpha2))};

export type Alpha3Code =
  | ${union(generated.map((c) => c.alpha3))};

/** Accepts a known code with autocomplete, but tolerates any string at runtime. */
export type FlagInput = CountryCode | Alpha3Code | (string & {});

export type FlagComponent = React.ComponentType<React.SVGProps<SVGSVGElement>>;
`,
);

// src/registry.ts
const loaders = generated
  .map((c) => `  ${c.alpha2}: () => import("./flags/${c.alpha2}"),`)
  .join("\n");
const names = generated
  .map((c) => `  ${c.alpha2}: ${quote(c.countryName)},`)
  .join("\n");
// Build alias maps with first-occurrence-wins dedup. flagpack occasionally
// ships a duplicate numeric code (e.g. AU is mislabeled 016, colliding with AS);
// we keep the first and warn rather than emit a broken object literal.
function aliasLines(keyOf, label) {
  const seen = new Set();
  const lines = [];
  for (const c of generated) {
    const key = keyOf(c);
    if (seen.has(key)) {
      console.warn(
        `[flaglet] duplicate ${label} code "${key}" (${c.alpha2}); keeping first`,
      );
      continue;
    }
    seen.add(key);
    lines.push(`  "${key}": "${c.alpha2}",`);
  }
  return lines.join("\n");
}

const alpha3 = aliasLines((c) => c.alpha3, "alpha-3");
const numeric = aliasLines((c) => c.numeric, "numeric");

writeFileSync(
  join(root, "src", "registry.ts"),
  `// AUTO-GENERATED by scripts/generate.mjs. Do not edit.
import type { CountryCode, FlagComponent } from "./types";

export const flagLoaders: Record<
  CountryCode,
  () => Promise<{ default: FlagComponent }>
> = {
${loaders}
};

export const countryNames: Record<CountryCode, string> = {
${names}
};

export const countryCodes = Object.keys(countryNames) as CountryCode[];

const alpha3ToAlpha2: Record<string, CountryCode> = {
${alpha3}
};

const numericToAlpha2: Record<string, CountryCode> = {
${numeric}
};

/** Normalize an alpha-2, alpha-3, or numeric code to a known alpha-2 code. */
export function resolveCode(input: string): CountryCode | undefined {
  if (!input) return undefined;
  const key = String(input).trim().toUpperCase();
  if (key in countryNames) return key as CountryCode;
  if (key in alpha3ToAlpha2) return alpha3ToAlpha2[key];
  const padded = key.padStart(3, "0");
  if (padded in numericToAlpha2) return numericToAlpha2[padded];
  return undefined;
}
`,
);

console.log(`[flaglet] generated ${generated.length} flag components`);
